name: 'Tester le Détecteur de Doublons'

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  run_detector:
    runs-on: ubuntu-latest
    permissions:
      issues: write 

    steps:
      # --- ÉTAPE DE DÉBOGAGE ---
      - name: Afficher les variables d'environnement (DEBUG)
        run: |
          echo "Vérification de INPUT_GITHUB_TOKEN (simulé):"
          if [ -n "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "secrets.GITHUB_TOKEN est PRÉSENT."
          else
            echo "secrets.GITHUB_TOKEN est VIDE ou NON DÉFINI."
          fi
      # --- FIN DÉBOGAGE ---

      - name: Lancer le Chercheur de Duplicata
        uses: carolinedanslesnuages/issue-duplicate-detector@main 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: '0.80' 
          duplicate-label: 'potential-duplicate'
